-- PRODUCT: 쇼핑물 상품 판매 정보
-- OFFLINE_SALE: 오프라인 상품 판매 정보

-- 조건: PRODUCT 테이블과 OFFLINE_SALE 테이블에서 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
SELECT DISTINCT PRODUCT.PRODUCT_CODE, PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT) AS SALES
FROM PRODUCT, OFFLINE_SALE
WHERE PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
ORDER BY PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT) DESC, PRODUCT_CODE ASC