-- ANIMAL_INS: 보호소에 들어온 동물
-- ANIMAL_OUTS: 보호소에서 입양 보낸 동물

-- 문제: 보호소에서 중성화 수술을 거친 동물의 정보 조회
-- 순서: 아이디, 종, 이름 

SELECT
    ANIMAL_INS.ANIMAL_ID,
    ANIMAL_INS.ANIMAL_TYPE,
    ANIMAL_INS.NAME
FROM
    ANIMAL_INS,
    ANIMAL_OUTS
WHERE
    ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID 
    AND ANIMAL_INS.SEX_UPON_INTAKE LIKE "Intact%" 
    AND ANIMAL_INS.SEX_UPON_INTAKE != ANIMAL_OUTS.SEX_UPON_OUTCOME
ORDER BY
    ANIMAL_INS.ANIMAL_ID;